### ISSUE TITLE
Poor error message when log file is empty

### ISSUE THREAD

**Issue by cshunger** [ibm-bluemix-mobile-services/bms-clientsdk-swift-analytics#5]
[ERROR] [bmssdk.analytics] sendAnalytics(completionHandler:) in /Users/cshunger/Downloads/MFPStarterIOSSwift/Pods/BMSAnalytics/Source/Logger/BMSLogger.swift:169 :: Request to send analytics data to the server has failed.

[ERROR] [bmssdk.logger] send(completionHandler:) in /Users/cshunger/Downloads/MFPStarterIOSSwift/Pods/BMSAnalytics/Source/Logger/BMSLogger.swift:72 :: Request to send client logs has failed.

Not a very good error message for not sending because the log file is empty.

**Comment by AnthonyOliveri** [comment]
Fixed in f9a2175
